name: 'Basic checks'
description: 'Basic Vue checks & builds for the template'
runs:
  using: "composite"
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - run: pnpm run lint:js:all
      shell: bash
    - run: pnpm run lint:css:all
      shell: bash
    - run: pnpm run tsc
      shell: bash
    - run: pnpm run build
      shell: bash
