name: 'Basic checks'
description: 'Basic Vue checks & builds for the template'
runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
    - name: Install dependencies
      run: bun install
      shell: bash
    - run: bun run lint:js:all
      shell: bash
    - run: bun run lint:css:all
      shell: bash
    - run: bun run tsc
      shell: bash
    - run: bun run build
      shell: bash
