name: Basic checks
description: 'Basic Nuxt checks & builds for the template'
runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v3
      with:
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - run: pnpm run lint:js .
      shell: bash
    - run: 'pnpm run lint:css **/*.{css,vue}'
      shell: bash
    - run: pnpm run tsc
      shell: bash
    - run: pnpm run build
      shell: bash
