name: 'Basic checks'
description: 'Basic Vue checks & builds for the template'
inputs:
  use-deno:
    description: 'If deno is used or not, used by custom daisyUI for now'
    default: false
runs:
  using: "composite"
  steps:
    # This is for building dependency daisyUI
    # TODO(Darkpi): Find some way to publish my custom one without needing a
    # build on all users.
    - name: cache deno installation and deno.land dependencies
      if: inputs.use-deno
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
        restore-keys: ${{ runner.os }}-deno-
        path: |
          /home/runner/.deno
          /home/runner/.cache/deno/deps/https/deno.land
    - uses: denoland/setup-deno@v1
      if: inputs.use-deno
      with:
        deno-version: v1.x
    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - run: pnpm run lint:js:all
      shell: bash
    - run: pnpm run lint:css:all
      shell: bash
    - run: pnpm run tsc
      shell: bash
    - run: pnpm run build
      shell: bash
