name: 'Basic checks'
description: 'Basic Vue checks & builds for the template'
runs:
  using: "composite"
  steps:
    - name: Cache pnpm modules
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.2.1
      with:
        run_install: true
    - run: pnpm run lint:js:all
      shell: bash
    - run: pnpm run lint:css:all
      shell: bash
    - run: pnpm run tsc
      shell: bash
    - run: pnpm run build
      shell: bash
