name: 'Basic checks'
description: 'Basic Vue checks & builds for the template'
runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
    - name: Install dependencies
      run: bun install
      shell: bash
    - run: bun run lint:js:all
      shell: bash
    - run: bun run lint:css:all
      shell: bash
    - run: bun run tsc
      shell: bash
    - run: bun run build
      shell: bash
