name: 'Basic checks'
description: 'Basic Vue checks & builds for the template'
runs:
  using: "composite"
  steps:
    - name: Setup mise
      uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3
    - name: Install dependencies
      run: bun install
      shell: bash
    - run: bun run lint:js:all
      shell: bash
    - run: bun run lint:css:all
      shell: bash
    - run: bun run tsc
      shell: bash
    - run: bun run build
      shell: bash
