// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCounter: typeof import('./src/components/simple-counter.vue')['default']
    TopNavbar: typeof import('./src/components/top-navbar.vue')['default']
  }
}

export {}
