// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AkarIconsCirclePlus: typeof import('~icons/akar-icons/circle-plus')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NotoV1RabbitFace: typeof import('~icons/noto-v1/rabbit-face')['default']
  }
}

export { }
