name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: peter50216/vue-template@456b89cf7f481fa4a01d8601f4d876da1f17e0de # v3
