name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - uses: peter50216/vue-template@f466daa74c8003d64ed7470b249109ecdc159907 # v2.4
